name: My First CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: TypeScript build
        run: npm run build

  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  deploy-staging:
    runs-on: ubuntu-latest

    needs: [test]
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Get Commit SHA
        run: echo "COMMIT_SHA=${{ github.sha }}" >> $GITHUB_ENV

      - name: Deploy to Staging
        uses: fjogeleit/http-request-action@v1.14.1
        with:
          url: "https://api.render.com/deploy/${{ secrets.STAGING_SERVICE_ID }}?key=rrEe0Mk75x0&ref=${{ env.COMMIT_SHA }}"
          method: "POST"
