name: Deploy to Production

on:
  workflow_dispatch:

jobs:
  deploy-production:
    runs-on: ubuntu-latest

    steps:
      - name: Get Commit SHA
        run: echo "COMMIT_SHA=${{ github.sha }}" >> $GITHUB_ENV

      - name: Deploy to Production
        uses: fjogeleit/http-request-action@v1.14.1
        with:
          url: https://api.render.com/deploy/${{ secrets.PRODUCTION_SERVICE_ID }}?key=ygalLUCiMf4&ref=${{ env.COMMIT_SHA }}
          method: "POST"
